import type { Exercise, Workout } from "./types"

export const exercises: Exercise[] = [
  {
    id: "1",
    name: "Bench Press",
    muscles: ["chest", "arms", "shoulders"],
    level: "intermediate",
    equipment: ["barbell"],
    description: "The barbell bench press is a classic chest exercise that builds strength and mass.",
    steps: [
      "Lie flat on a bench with feet on the floor",
      "Grip the bar slightly wider than shoulder-width",
      "Lower the bar to your chest in a controlled manner",
      "Press the bar back up to the starting position",
      "Repeat for desired reps",
    ],
    tips: ["Keep your shoulders back and down", "Use a full range of motion", "Control the descent"],
    commonMistakes: ["Bouncing the bar off your chest", "Flaring elbows too wide", "Partial range of motion"],
    videoUrl: "https://www.youtube.com/embed/SCVCLChPQFY",
    image: "/barbell-bench-press.png",
  },
  {
    id: "2",
    name: "Barbell Squat",
    muscles: ["legs", "glutes"],
    level: "intermediate",
    equipment: ["barbell"],
    description: "The barbell squat is the king of leg exercises, building lower body strength and mass.",
    steps: [
      "Place the barbell on your shoulders",
      "Stand with feet shoulder-width apart",
      "Lower your body by bending knees and hips",
      "Go down until thighs are parallel to ground",
      "Drive through heels to return to start",
    ],
    tips: ["Keep your chest up", "Drive through your heels", "Maintain a neutral spine"],
    commonMistakes: ["Knees caving inward", "Leaning too far forward", "Partial range of motion"],
    videoUrl: "https://www.youtube.com/embed/Dy28eq2PjcM",
    image: "/barbell-squat-leg-exercise.jpg",
  },
  {
    id: "3",
    name: "Push-ups",
    muscles: ["chest", "arms", "shoulders"],
    level: "beginner",
    equipment: ["bodyweight"],
    description: "A fundamental bodyweight exercise that builds chest, shoulder, and tricep strength.",
    steps: [
      "Start in a plank position",
      "Lower your body until chest nearly touches the floor",
      "Push yourself back to the starting position",
      "Keep your body in a straight line",
      "Repeat for desired reps",
    ],
    tips: ["Keep core tight", "Full range of motion", "Controlled pace"],
    commonMistakes: ["Sagging hips", "Flaring elbows too wide", "Going too fast"],
    videoUrl: "https://www.youtube.com/embed/IODxDxX7oi4",
    image: "/push-ups-bodyweight-exercise.jpg",
  },
  {
    id: "4",
    name: "Pull-ups",
    muscles: ["back", "arms"],
    level: "advanced",
    equipment: ["bodyweight"],
    description: "An advanced bodyweight exercise that builds back and bicep strength.",
    steps: [
      "Grip the bar with hands shoulder-width apart",
      "Pull your body up until chin is above the bar",
      "Lower yourself back to the starting position",
      "Keep core engaged throughout",
      "Repeat for desired reps",
    ],
    tips: ["Engage your lats", "Controlled descent", "Avoid swinging"],
    commonMistakes: ["Using momentum", "Partial range of motion", "Gripping too wide"],
    videoUrl: "https://www.youtube.com/embed/eGo4IYlbE5g",
    image: "/pull-ups-back-exercise.jpg",
  },
  {
    id: "5",
    name: "Plank",
    muscles: ["abs"],
    level: "beginner",
    equipment: ["bodyweight"],
    description: "A core-building exercise that strengthens the abs and entire core.",
    steps: [
      "Start in a forearm plank position",
      "Keep your body in a straight line",
      "Engage your core muscles",
      "Hold this position for time",
      "Rest and repeat",
    ],
    tips: ["Keep hips level", "Engage your core", "Breathe steadily"],
    commonMistakes: ["Sagging hips", "Lifting hips too high", "Holding breath"],
    videoUrl: "https://www.youtube.com/embed/pSHjTRCQxIw",
    image: "/plank-core-exercise.jpg",
  },
  {
    id: "6",
    name: "Deadlift",
    muscles: ["back", "legs", "glutes"],
    level: "advanced",
    equipment: ["barbell"],
    description: "The deadlift is a compound movement that works the entire posterior chain.",
    steps: [
      "Stand with feet hip-width apart",
      "Grip the bar just outside your legs",
      "Keep your back straight as you lift",
      "Drive through your heels",
      "Stand fully upright at the top",
    ],
    tips: ["Keep the bar close to your body", "Neutral spine", "Strong grip"],
    commonMistakes: ["Rounding your back", "Starting with hips too high", "Bar too far from body"],
    videoUrl: "https://www.youtube.com/embed/SCVCLChPQFY",
    image: "/deadlift-back-exercise.jpg",
  },
  {
    id: "7",
    name: "Dumbbell Curls",
    muscles: ["arms"],
    level: "beginner",
    equipment: ["dumbbell"],
    description: "A fundamental arm exercise that isolates the biceps.",
    steps: [
      "Stand with dumbbells at your sides",
      "Curl the dumbbells up to shoulder height",
      "Keep elbows stationary",
      "Lower back to starting position",
      "Repeat for desired reps",
    ],
    tips: ["Controlled movements", "Full range of motion", "Squeeze at the top"],
    commonMistakes: ["Using momentum", "Moving elbows", "Partial range of motion"],
    videoUrl: "https://www.youtube.com/embed/SCVCLChPQFY",
    image: "/dumbbell-curls-biceps-exercise.jpg",
  },
  {
    id: "8",
    name: "Shoulder Press",
    muscles: ["shoulders", "arms"],
    level: "intermediate",
    equipment: ["barbell"],
    description: "A pressing movement that builds shoulder strength and stability.",
    steps: [
      "Stand with the barbell at shoulder height",
      "Press the bar overhead",
      "Lower the bar back to shoulders",
      "Keep core tight",
      "Repeat for desired reps",
    ],
    tips: ["Full body tension", "Neutral spine", "Controlled descent"],
    commonMistakes: ["Arching back too much", "Partial range of motion", "Unstable base"],
    videoUrl: "https://www.youtube.com/embed/SCVCLChPQFY",
    image: "/shoulder-press-exercise.png",
  },
]

export const workouts: Workout[] = [
  {
    id: "w1",
    name: "Full Body Beginner",
    duration: 4,
    level: "beginner",
    sessionsPerWeek: 3,
    description: "Perfect for beginners starting their fitness journey. 3 sessions per week.",
    exercises: [
      { exerciseId: "1", sets: 3, reps: 8, rest: 90 },
      { exerciseId: "3", sets: 3, reps: 10, rest: 60 },
      { exerciseId: "2", sets: 3, reps: 8, rest: 90 },
      { exerciseId: "5", sets: 3, reps: 30, rest: 45 },
    ],
    image: "/full-body-beginner-workout.jpg",
  },
  {
    id: "w2",
    name: "Mass Building - 8 Weeks",
    duration: 8,
    level: "intermediate",
    sessionsPerWeek: 4,
    description: "Build muscle mass with a focused split routine. 4 sessions per week.",
    exercises: [
      { exerciseId: "1", sets: 4, reps: 6, rest: 120 },
      { exerciseId: "6", sets: 4, reps: 5, rest: 120 },
      { exerciseId: "2", sets: 4, reps: 6, rest: 120 },
      { exerciseId: "8", sets: 3, reps: 8, rest: 90 },
    ],
    image: "/mass-building-workout-program.jpg",
  },
  {
    id: "w3",
    name: "Home Workouts",
    duration: 6,
    level: "beginner",
    sessionsPerWeek: 4,
    description: "Train at home with minimal equipment. Bodyweight focused.",
    exercises: [
      { exerciseId: "3", sets: 3, reps: 12, rest: 60 },
      { exerciseId: "4", sets: 3, reps: 8, rest: 90 },
      { exerciseId: "5", sets: 3, reps: 45, rest: 60 },
    ],
    image: "/home-workout-bodyweight.jpg",
  },
  {
    id: "w4",
    name: "Push Pull Legs Advanced",
    duration: 12,
    level: "advanced",
    sessionsPerWeek: 6,
    description: "Advanced PPL split for experienced lifters. 6 sessions per week.",
    exercises: [
      { exerciseId: "1", sets: 4, reps: 6, rest: 120 },
      { exerciseId: "6", sets: 4, reps: 5, rest: 120 },
      { exerciseId: "2", sets: 4, reps: 6, rest: 120 },
    ],
    image: "/push-pull-legs-advanced-split.jpg",
  },
]
